package org.CS5800.Pizzas;

public enum Topping {
    PEPPERONI, SAUSAGE, MUSHROOMS, BACON, ONIONS, EXTRA_CHEESE, PEPPERS,
    CHICKEN, OLIVES, SPINACH, TOMATO_AND_BASIL, BEEF, HAM, PESTO, SPICY_PORK,
    HAM_AND_PINEAPPLE;
}
